### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by johnphrum** [PsychoPatate/No-YT-Chat#2]
How can this script be uninstalled?

**Comment by JKerboeuf** [comment]
Hi 👋
The method can vary depending on the add-on you are using to run the script, but in most case you would need to open the add-on's menu and find the button or icon to uninstall it
### If you are using GreaseMonkey
1. Click on the GreaseMonkey icon
2. Click on "No Youtube Chat"
3. Click "Uninstall" with the trash can icon

### If you are using TamperMonkey
1. Click on the TamperMonkey icon
2. Click on "Dashboard"
3. There you should find a list of your installed scripts
4. Find the line for "No Youtube Chat" and click "Delete" (the trash can icon on the right side)

Hope this helps, have a nice day :)
